displayName=Better Map
author=truenosus
description=A general improvement to the default Jagex map. Compatible with most plugins that draw icons on map.
tags=map,improvement,tooltip,icons,general
version=1.0.0
plugins=com.bettermap.BetterMapPlugin
build=standard
